version: '3.8'
services:
  tpm-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3.9 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/api
    ports:
      - "8000:8000"
